### PR TITLE
Allow user control peers count in announce 

### PR DESCRIPTION
**Pull request by batkom**
In normal situations, the 50-100 limits built into hefur are optimal. But advanced control over these limits can be useful for private torrents that can't use PEX or DHT.
added options 
-min-numwant (default 50) - the minimum number of peers that will be returned in the announcement. Since numwant is optional, if it is omitted in client request, the default value will be used. User can raise this limit to raise peers count without enabling PEX.
-max-numwant (default 100) the maximum number of peers that will be returned in the announcement.

### CODE REVIEW

**Comment by abique** [comment]
Hi!

Thank you very much for the PR, I've found a few style improvements if you have time for it otherwise I'll do it myself later.

Cheers,
Alex

**Comment by batkom** [comment]
Sure, i think i can do it. What kind of improvements do you mean?

**Comment by abique** [comment]
It is in the review comments.

**Comment by abique** [comment]
Never mind I do it ;-)

**Pull request merged**
